import React from 'react'

export default function Exercise06() {
  return (
    <div>
      <p className='overflow-y-scroll w-[400px] h-[200px] mt-[50px]'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Incidunt eveniet quisquam iste quam sit exercitationem optio quia? Fugiat animi excepturi quaerat quibusdam tempore, voluptatem veritatis quae vel odit autem consequatur?
      Iure illo, inventore ducimus, reprehenderit autem repellat quasi non ex possimus doloremque commodi officia accusamus accusantium tenetur ipsa corrupti earum ipsam recusandae, nihil quam quia? Veniam sed illo vero corrupti!
      Suscipit earum exercitationem enim, accusamus iste explicabo saepe cupiditate ipsum ipsa ducimus, quae molestiae omnis odit ullam quidem aliquid. Quas consectetur, asperiores sit ipsa blanditiis omnis in beatae nam voluptatibus.
      Voluptas eaque labore officiis libero iure quae sed eum quos laborum aut omnis repudiandae, dolor, hic reprehenderit explicabo non fugiat vero doloremque consequuntur at. Repellat incidunt cum suscipit iusto reprehenderit!
      Reiciendis aut ipsum ex eveniet, voluptates sed aperiam neque maiores exercitationem dicta, tempore velit quam magnam suscipit reprehenderit voluptas est. Dolorum accusamus corporis corrupti ducimus explicabo asperiores ullam? Suscipit, minima!
      Libero officia consectetur animi laborum asperiores vero eius id sunt error placeat consequatur, aperiam exercitationem, dicta temporibus, similique dolorem veritatis dolores. Alias, facilis perferendis? Excepturi, ducimus unde? Ad, incidunt ullam.
      Consequatur velit enim debitis tempora illo repellat aspernatur sed voluptates ipsam, ut eius illum obcaecati esse nam nemo corrupti, blanditiis doloribus error reprehenderit! Accusamus quis tempore, laboriosam enim tempora autem.
      Iusto vel animi odit impedit debitis, delectus, a aliquam unde dolores sequi repellendus sunt hic. Autem ad cum veritatis voluptate ea fuga a, dolores dignissimos unde provident incidunt maxime nesciunt?
      Incidunt architecto velit eos magni. Qui magnam voluptatum doloribus sequi neque, nisi sint alias aspernatur unde eum enim adipisci doloremque dignissimos dolorem tempora ipsum illum et dolorum. Nulla, perferendis quam.
      Molestias, veniam perferendis voluptate laboriosam quas mollitia quam, corrupti ad maxime ut veritatis est ducimus sapiente? Quae obcaecati nulla corrupti eveniet ex at, quo odio enim, in porro blanditiis dicta?
      Sint soluta ea, veritatis voluptates blanditiis delectus, dicta fuga, distinctio qui est eveniet unde exercitationem et non ex nulla? Deserunt praesentium cum porro dolore asperiores, consectetur exercitationem ipsam accusantium reiciendis.
      Qui in aut voluptatum doloribus reprehenderit ducimus illo cum expedita optio blanditiis sunt obcaecati laboriosam dignissimos, facere perspiciatis asperiores doloremque quibusdam aperiam tempora velit, praesentium, maxime ratione repellendus? Quibusdam, nam!
      Laboriosam voluptatibus eligendi, iure aperiam repudiandae nesciunt quia modi libero, eaque aspernatur quas nostrum nulla corrupti recusandae natus corporis quaerat rem. Recusandae sapiente corrupti iure fugit fuga quaerat alias adipisci.
      Ipsa doloremque nostrum ad dicta omnis libero numquam nam, facere eius sunt. Recusandae, nobis reiciendis, magnam omnis ratione, excepturi rem sed obcaecati velit ullam debitis minima nam labore fugit maxime?
      Assumenda, fuga dicta, sit iste, magnam velit laudantium vitae a molestiae necessitatibus provident officia deleniti repellendus in. Pariatur corrupti repellendus similique aspernatur non excepturi dignissimos, fugit est natus harum perspiciatis.
      Praesentium maxime neque velit nisi nostrum! Provident fugit quo officia reprehenderit suscipit! Ducimus molestiae officia quaerat praesentium nihil? Ducimus expedita hic, ipsum cupiditate eveniet similique sed fugiat rerum distinctio omnis?
      Enim id recusandae mollitia soluta laborum nihil accusamus optio assumenda magnam sequi perspiciatis ab, repellendus quo numquam consectetur ipsam, nesciunt delectus pariatur neque maxime eum. Alias ratione quia facilis necessitatibus.
      Alias possimus, tenetur quos atque iusto nisi molestiae neque ipsum officia nam beatae laborum repellendus est odio debitis corporis, laudantium dolore nemo similique dicta eos. Aperiam ea magni corrupti nesciunt?
      Dolor, eius, laborum explicabo illum dignissimos fugiat in repudiandae dolorum ratione minus, corrupti praesentium asperiores nam magni nihil modi vel perferendis deleniti reprehenderit laboriosam rerum repellat rem natus! Perferendis, iusto.
      Quisquam, explicabo corporis. Rem iure corrupti ipsum tempore optio nisi! Qui adipisci corrupti nihil soluta, fugiat totam natus debitis eaque. Ipsum inventore voluptatibus ab, veritatis neque soluta delectus provident fugiat.
      Sit vero obcaecati omnis nemo veritatis! Voluptas, aperiam natus hic provident, enim deserunt aut maiores ipsum asperiores maxime excepturi, illo tenetur recusandae iusto laborum assumenda obcaecati. Atque magni at laboriosam.
      Pariatur expedita tempora voluptatibus. Dolorem accusantium deleniti vel maiores expedita repudiandae temporibus maxime sunt labore, impedit, quibusdam eveniet non! Pariatur ex officia sunt hic eveniet quibusdam debitis similique eos adipisci.
      Quis, laboriosam numquam est repudiandae placeat nesciunt, magni vel, ratione temporibus odio laudantium sint repellendus maxime nulla voluptatibus obcaecati. Excepturi magnam corrupti eligendi totam veniam optio cupiditate magni aut nam?
      Vitae sed aliquam aspernatur exercitationem laborum! Laudantium voluptatum beatae minus libero fugit animi aliquid officia a. Cumque saepe necessitatibus dicta magni quibusdam, molestias ex aliquam obcaecati labore, possimus ea accusamus.
      Repudiandae doloribus vero ipsa dolor pariatur voluptate quos magni nulla minima temporibus labore debitis quibusdam accusamus mollitia amet minus quo aspernatur dicta blanditiis, cum autem perferendis tenetur enim tempore? Minus!
      Id eum recusandae molestiae odit doloremque? Libero quidem deleniti, deserunt repellendus blanditiis rerum quis doloremque natus! Amet harum, numquam doloribus iste ducimus incidunt, accusantium sint animi quas consequuntur deleniti nisi!
      Quas maxime eius ullam aliquid dolore fuga sed animi nesciunt, recusandae amet suscipit vel, alias saepe. Autem impedit explicabo pariatur repellat? Praesentium quidem maxime laborum accusamus quod corporis odit eos?
      Suscipit deleniti cumque, rerum maiores officiis modi iusto sint sunt ipsa deserunt ex explicabo quo aliquam, tempore facere minus vitae? Recusandae optio ipsa ab ea quibusdam laudantium ipsum ducimus necessitatibus!
      In amet dolore porro exercitationem doloremque officia perspiciatis delectus dolorem eaque culpa quibusdam ea nihil repellendus necessitatibus blanditiis, debitis magni dolores veniam possimus, tenetur, minima corporis eum! Dolor, repudiandae et?
      Vel, doloribus error? Natus perferendis distinctio adipisci quos nobis porro. Reiciendis iusto, quam autem repellendus officiis non eveniet. Tenetur voluptates quibusdam ratione itaque ipsum perferendis ducimus voluptatibus accusantium consequuntur voluptas.
      Cum iste, incidunt, ad debitis pariatur laudantium vel, sequi vero architecto ab velit quos ratione! Maxime vitae, commodi aliquam porro minus asperiores voluptatum mollitia et at enim, dolor tempora! In.
      Sed voluptas dicta, autem delectus sit enim, similique nesciunt reprehenderit aspernatur inventore quos aliquid ea obcaecati, porro perferendis? Aliquam, cupiditate provident. Qui asperiores, dolore hic voluptas praesentium numquam eaque soluta!
      Tempora sint dolorem recusandae inventore deserunt odit odio sequi quae! Consectetur accusamus harum voluptate a unde architecto illo, voluptas praesentium, enim dolorem officia non laboriosam nemo sunt fuga assumenda ut!
      Expedita, voluptate assumenda ea commodi sapiente non, eligendi optio nostrum, nihil incidunt obcaecati facere doloribus eum at voluptatem quia veniam. Reiciendis deserunt ea beatae quidem minus error amet doloribus facilis!
      Asperiores, odio. Doloribus inventore ut reiciendis, ipsum laborum necessitatibus similique odio suscipit accusamus rerum commodi voluptates temporibus cupiditate quis modi distinctio porro pariatur? Exercitationem vel aspernatur veniam harum et quaerat.
      Sint quia facere, rem minus quisquam neque mollitia voluptas. Officia fugit molestiae suscipit nobis inventore. Eius vitae fugiat minus, accusantium sed labore. Accusantium ducimus facere ratione perferendis voluptate obcaecati rerum?
      Laborum, corrupti. Fugit sunt voluptatem commodi, delectus minus soluta tenetur saepe quo optio modi. Hic accusantium voluptatum molestiae. Culpa provident iste aspernatur. Officia amet eius vel culpa quasi in molestias?
      Facere dolore ut, eius libero ea necessitatibus aut beatae voluptate ipsam reiciendis ipsum, tempora sed. Iste consectetur dolore, ducimus corrupti odio deserunt fugiat veniam ratione, tempore obcaecati, aliquid dignissimos cum.
      Quia animi voluptatibus, vero laboriosam non perspiciatis magni voluptates. Accusantium minus quisquam perspiciatis. Consequuntur perferendis nulla non, animi temporibus nihil laudantium ullam odio quidem fugit dolorem enim fuga error libero!
      Voluptas necessitatibus suscipit magnam? Explicabo praesentium consequatur aliquid expedita! At nostrum nulla saepe iste tempore, officiis sint aliquid consequatur! Ipsum perferendis itaque dolore exercitationem nobis iste ut laboriosam numquam doloremque.
      Nesciunt voluptates harum at laudantium veritatis accusantium corrupti veniam iure assumenda consectetur temporibus soluta, ratione laborum libero dolor nam quae possimus nemo beatae natus numquam fuga! Facilis cumque possimus dignissimos?
      Libero omnis et corrupti quidem, molestiae totam unde ut nulla asperiores, quos, ipsam non ipsum facere iure architecto doloribus! Hic ab beatae tempora, id quo deleniti soluta aperiam et aspernatur!
      Quos aut unde blanditiis fugiat, harum quibusdam eveniet doloremque non et. Ut similique ea distinctio dignissimos libero consequuntur ullam molestias atque eos iste porro accusamus dicta repellat omnis, nostrum cupiditate.
      Aspernatur quas earum error nostrum mollitia repudiandae quo facere sequi nulla rem neque, magnam veritatis odit sint iusto provident sed iste a aliquam rerum ea doloribus. Ab molestiae tempora error!
      Esse tempora dicta magni odio consequuntur, minus accusamus ut saepe dolorum odit accusantium alias. Odio, nesciunt ea voluptatum explicabo repellendus veritatis vitae porro deserunt dolores, aspernatur cupiditate quod animi dicta.
      Pariatur deleniti voluptatum, illo provident corporis ipsa neque? Sint, delectus? Deleniti excepturi doloribus aliquid magni officiis sed porro rerum non tempora omnis laudantium odio, tenetur minima. Iusto impedit ut doloribus!
      Hic molestias adipisci, aperiam nobis, quisquam ut illum voluptas tempora exercitationem dolor pariatur, aspernatur obcaecati placeat fugiat sint id architecto. Praesentium nihil eaque perferendis itaque illo ducimus architecto corrupti pariatur.
      Sint non earum explicabo itaque eaque ad veritatis fugiat exercitationem, molestias voluptates inventore consectetur tenetur tempore recusandae expedita, similique dignissimos nostrum ut eos eligendi. Distinctio recusandae molestias mollitia unde pariatur.
      Eaque alias assumenda ipsam corporis maxime nam quam ipsa sequi similique explicabo iure quo ratione nisi molestias ullam nemo, quos libero. Sunt consequuntur ratione dicta officiis nobis temporibus dolore? Sit.
      Doloribus aliquid iure asperiores natus alias quos nam, adipisci autem corrupti aliquam ex doloremque. Repudiandae, vero fuga? Iste fugit reiciendis, qui, placeat maxime blanditiis quisquam modi cupiditate amet beatae iure?</p>
    </div>
  )
}
